[package]
name = "xdg-open"
version = "0.1.0"
authors = ["Stone Tickle <lattis@mochiro.moe>"]

[dependencies]
mime_guess = "1.8.6"
regex = "1"
lazy_static = "1.2.0"
toml = "0.4"
dirs = "1"
clap = "2"
